[book]
authors = ["Eric Shimizu Karbstein <gr41.j4ck@gmail.com>"]
language = "en"
multilingual = false
src = "src"
title = "The Carp Programming Language"

[output.html]
default-theme = "rust"
preferred-dark-theme = "coal"
git-repository-url = "https://github.com/GrayJack/carp-book"
git-repository-icon = "fa-github"
